### PR TITLE
exit needs tx bytes/outputTx

### PR DESCRIPTION
**Pull request by InoMurko**

### CODE REVIEW

**Comment by InoMurko** [comment]
not a single test failed. odd.

**Comment by souradeep-das** [comment]
yeah the `expectEvent` in the tests allow unspecified event args. Let's still add the new args to the tests? `PaymentStartStandardExit.test.js`

**Review by kevsul — APPROVED** [review]
Looks good

**Comment by InoMurko** [comment]
> Looks good

thank you, you too

**Pull request merged**
